"use client";
import { apiFetch } from "@/lib/api";
import {useMemo,useState,type FormEvent} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import "./agenda-calendar.css";

type Item={id:number;client_id:number;service_id:number;service_name:string;start_at:string;duration:number;status:string;amount:number;notes?:string};
type Client={id:number;name:string;phone?:string;vehicle?:string;plate?:string;user_id?:string};
type Service={id:number;name:string;duration:number;booking_duration:number;category?:string};
type Block={id:string;status:string;data:{title?:string;start?:string;end?:string}};
type Props={bookings:Item[];clients:Client[];services:Service[];blocks:Block[];onRefresh:()=>Promise<void>;onBlock:()=>void;onEditBlock:(block:Block)=>void};
type Form={clientId:string;serviceId:string;startAt:string;notes:string};
const blank:Form={clientId:"",serviceId:"",startAt:"",notes:""};
const days=["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"];
const pad=(n:number)=>String(n).padStart(2,"0");
const key=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parse=(s:string)=>{const [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)};
const add=(d:Date,n:number)=>new Date(d.getFullYear(),d.getMonth(),d.getDate()+n);
const monday=(d:Date)=>add(d,-((d.getDay()+6)%7));
const label=(s:string)=>`${s.slice(8,10)}/${s.slice(5,7)}/${s.slice(0,4)} às ${s.slice(11,16)}`;
const currency=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n/100);
const active=(s:string)=>s==="solicitado"||s==="agendado"||s==="em andamento";

export default function AgendaCalendar({bookings,clients,services,blocks,onRefresh,onBlock,onEditBlock}:Props){
 const [view,setView]=useState<"month"|"week"|"day">("month"),[anchor,setAnchor]=useState(key(new Date())),[selected,setSelected]=useState<Item|null>(null),[mode,setMode]=useState<"new"|"edit"|null>(null),[form,setForm]=useState<Form>(blank),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const customer=(id:number)=>clients.find(c=>c.id===id);
 const service=(id:number)=>services.find(s=>s.id===id);
 const visible=useMemo(()=>bookings.filter(b=>b.status!=="cancelado").sort((a,b)=>a.start_at.localeCompare(b.start_at)),[bookings]);
 const base=parse(anchor),week=monday(base),monthStart=monday(new Date(base.getFullYear(),base.getMonth(),1));
 const monthEnd=new Date(base.getFullYear(),base.getMonth()+1,0);
 const monthCount=Math.ceil((Math.round((monthEnd.getTime()-monthStart.getTime())/86400000)+1)/7)*7;
 const grid=view==="day"?[base]:Array.from({length:view==="week"?7:monthCount},(_,i)=>add(view==="week"?week:monthStart,i));
 const heading=view==="month"?new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(base):view==="week"?`${pad(week.getDate())}/${pad(week.getMonth()+1)} a ${pad(add(week,6).getDate())}/${pad(add(week,6).getMonth()+1)}`:new Intl.DateTimeFormat("pt-BR",{dateStyle:"full"}).format(base);
 const currentService=service(Number(form.serviceId));
 const start=new Date(form.startAt).getTime(),end=start+(currentService?.booking_duration||30)*60000;
 const conflict=!!form.startAt&&!!currentService&&Number.isFinite(start)&&(
  bookings.some(b=>b.id!==selected?.id&&active(b.status)&&start<new Date(b.start_at).getTime()+b.duration*60000&&end>new Date(b.start_at).getTime())||
  blocks.some(b=>b.status!=="cancelado"&&b.data.start&&b.data.end&&start<new Date(b.data.end).getTime()&&end>new Date(b.data.start).getTime()));
 const navigate=(step:number)=>{const d=view==="month"?new Date(base.getFullYear(),base.getMonth()+step,Math.min(base.getDate(),28)):add(base,step*(view==="week"?7:1));setAnchor(key(d))};
 const openNew=(day?:string)=>{setSelected(null);const weekday=day?new Date(day+"T12:00:00").getDay():new Date().getDay();const opening=weekday===6?"08:00":"15:00";setForm({...blank,startAt:day?`${day}T${opening}`:""});setError("");setMode("new")};
 const openEdit=()=>{if(!selected)return;setForm({clientId:String(selected.client_id),serviceId:String(selected.service_id),startAt:selected.start_at.slice(0,16),notes:selected.notes||""});setError("");setMode("edit")};
 const save=async(e:FormEvent)=>{e.preventDefault();if(conflict){setError("Horário ocupado ou bloqueado. Escolha outro horário.");return}setBusy(true);setError("");try{const r=await apiFetch("/api/data",{method:mode==="new"?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({table:"bookings",...(mode==="edit"?{action:"edit",id:selected?.id}:{}),...form})}),j=await r.json();if(!r.ok)throw Error(j.error||"Não foi possível salvar.");await onRefresh();setMode(null);setSelected(null);setAnchor(form.startAt.slice(0,10))}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar.")}finally{setBusy(false)}};
 const cancel=async()=>{if(!selected||!window.confirm("Cancelar este agendamento? Ele deixará de ocupar o horário e aparecerá como cancelado na área do cliente."))return;setBusy(true);setError("");try{const r=await apiFetch("/api/data",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({table:"bookings",id:selected.id,status:"cancelado"})}),j=await r.json();if(!r.ok)throw Error(j.error||"Não foi possível cancelar.");await onRefresh();setSelected(null)}catch(e){setError(e instanceof Error?e.message:"Falha ao cancelar.")}finally{setBusy(false)}};
 return <section className="agenda-shell">
  <div className="agenda-toolbar"><div><h2>Agenda de atendimentos</h2><p>Confira a disponibilidade e registre manualmente os pedidos recebidos pelo WhatsApp.</p></div><div className="agenda-actions"><Button onClick={()=>openNew()}>Novo agendamento</Button><Button variant="outline" onClick={onBlock}>Bloquear horário</Button></div></div>
  <div className="agenda-nav"><div className="agenda-move"><Button type="button" variant="outline" onClick={()=>navigate(-1)} aria-label="Período anterior">‹</Button><Button type="button" variant="outline" onClick={()=>setAnchor(key(new Date()))}>Hoje</Button><Button type="button" variant="outline" onClick={()=>navigate(1)} aria-label="Próximo período">›</Button><strong>{heading}</strong></div><div className="agenda-view" role="group" aria-label="Visualização da agenda">{([['month','Mês'],['week','Semana'],['day','Dia']] as const).map(([v,t])=><Button key={v} variant={view===v?"default":"outline"} onClick={()=>setView(v)}>{t}</Button>)}</div><Input className="agenda-date" type="date" aria-label="Ir para data" value={anchor} onChange={e=>e.target.value&&setAnchor(e.target.value)}/></div>
  <div className={`agenda-grid agenda-${view}`}>{grid.map((d,i)=>{const day=key(d),events=visible.filter(b=>b.start_at.slice(0,10)===day),dayBlocks=blocks.filter(b=>b.status!=="cancelado"&&b.data.start?.slice(0,10)===day);return <div className={`agenda-day ${d.getMonth()!==base.getMonth()&&view==="month"?"outside":""} ${day===key(new Date())?"is-today":""}`} key={day}><div className="agenda-day-head"><button type="button" onClick={()=>{setAnchor(day);setView("day")}}>{view!=="day"&&<span>{days[i%7]} </span>}{pad(d.getDate())}</button><button className="agenda-add" type="button" aria-label={`Agendar em ${day}`} onClick={()=>openNew(day)}>+</button></div><div className="agenda-events">{events.map(b=><button type="button" className={`agenda-event ${b.status==="concluido"?"done":""}`} key={b.id} onClick={()=>{setError("");setSelected(b)}}><strong>{b.start_at.slice(11,16)} · {customer(b.client_id)?.name||"Cliente"}</strong><span>{customer(b.client_id)?.vehicle||"Veículo não informado"}{customer(b.client_id)?.plate?` · ${customer(b.client_id)?.plate}`:""}</span><span>{b.service_name}</span></button>)}{dayBlocks.map(b=><span className="agenda-block" key={b.id}>Bloqueado · {b.data.title||"Indisponível"}</span>)}</div></div>})}</div>
  <p className="agenda-hint">Ao salvar, o agendamento aparece na área do cliente se o cadastro escolhido estiver vinculado à conta dele.</p>
  {blocks.length>0&&<details className="agenda-block-list"><summary>Horários bloqueados ({blocks.filter(b=>b.status!=="cancelado").length})</summary>{blocks.filter(b=>b.status!=="cancelado").map(b=><p key={b.id}>{b.data.title||"Bloqueio"} · {b.data.start&&label(b.data.start)} a {b.data.end&&label(b.data.end)} <Button variant="outline" size="sm" onClick={()=>onEditBlock(b)}>Editar</Button></p>)}</details>}
  <Dialog open={!!selected&&!mode} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="agenda-dialog"><DialogHeader><DialogTitle>{selected?.service_name}</DialogTitle><DialogDescription>Detalhes do agendamento</DialogDescription></DialogHeader>{selected&&<><dl className="agenda-details"><div><dt>Cliente</dt><dd>{customer(selected.client_id)?.name||"Cliente"}</dd></div><div><dt>Veículo</dt><dd>{customer(selected.client_id)?.vehicle||"Não informado"} {customer(selected.client_id)?.plate||""}</dd></div><div><dt>Data e horário</dt><dd>{label(selected.start_at)} · {selected.duration} min</dd></div><div><dt>Status</dt><dd>{selected.status}</dd></div><div><dt>Valor</dt><dd>{currency(selected.amount)}</dd></div><div><dt>Observações</dt><dd>{selected.notes||"—"}</dd></div></dl>{error&&<p className="error" role="alert">{error}</p>}<div className="agenda-dialog-actions">{["agendado","solicitado"].includes(selected.status)&&<><Button onClick={openEdit}>Editar / reagendar</Button><Button variant="outline" disabled={busy} onClick={cancel}>Cancelar</Button></>}{customer(selected.client_id)?.phone&&<a target="_blank" rel="noreferrer" href={`https://wa.me/55${customer(selected.client_id)?.phone?.replace(/\D/g,"")}?text=${encodeURIComponent(`Olá! Seu atendimento na Feijão Detailer está agendado para ${label(selected.start_at)}: ${selected.service_name}.`)}`}>Preparar WhatsApp</a>}</div></>}</DialogContent></Dialog>
  <Dialog open={!!mode} onOpenChange={v=>{if(!v&&!busy)setMode(null)}}><DialogContent className="agenda-dialog"><DialogHeader><DialogTitle>{mode==="new"?"Novo agendamento":"Editar / reagendar"}</DialogTitle><DialogDescription>O horário será confirmado ao salvar. Pedidos pelo WhatsApp são lançados manualmente aqui.</DialogDescription></DialogHeader><form className="ops-form" onSubmit={save}><label>Cliente<select required disabled={mode==="edit"} value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}{c.vehicle?` · ${c.vehicle}`:""}</option>)}</select></label>{mode==="new"&&form.clientId&&!customer(Number(form.clientId))?.user_id&&<p className="agenda-hint">Este cadastro ainda não está vinculado a uma conta. O agendamento ficará salvo, mas só aparecerá na área do cliente após o vínculo.</p>}<label>Serviço<select required value={form.serviceId} onChange={e=>setForm({...form,serviceId:e.target.value})}><option value="">Selecione</option>{services.filter(s=>s.category!=="Planos mensais").map(s=><option key={s.id} value={s.id}>{s.name} · chegada {s.booking_duration||30} min · previsão {s.duration} min</option>)}</select></label><label>Data e horário<Input required type="datetime-local" value={form.startAt} onChange={e=>setForm({...form,startAt:e.target.value})}/></label><label>Observações<Input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{conflict&&<p className="error" role="alert">Horário ocupado ou bloqueado. Escolha outro horário.</p>}{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy||conflict}>{busy?"Salvando...":"Salvar agendamento"}</Button></form></DialogContent></Dialog>
 </section>;
}
