"use client";
import { withBase } from "@/lib/base";

import {useState} from 'react';
import {ArrowUpRight,Bell,CalendarDays,Camera,Car,Check,CheckCircle2,ChevronRight,Clock3,Download,FileText,Gift,Heart,ShieldCheck,Sparkles,Wrench} from 'lucide-react';
import {Button} from '@/components/ui/button';
import './customer-portal-preview.css';
import './customer-portal-preview-admin.css';

type View='customerHome'|'garagePreview'|'trackingPreview'|'reportsPreview'|'protectionsPreview'|'benefitsPreview';
const heroImage='/service-images/studio-editorial.webp';
const washImage='/service-images/limpeza-premium-v2.png';
const timeline=['Veículo recebido','Inspeção inicial','Preparação','Serviço em execução','Finalização','Controle de qualidade','Pronto para entrega'];

export default function CustomerPortalPreview({view,navigate,adminPreview=false}:{view:View;navigate:(tab:string)=>void;adminPreview?:boolean}){
 const [adminView,setAdminView]=useState<View>(view);
 const [expanded,setExpanded]=useState(false),[compare,setCompare]=useState(50),[copied,setCopied]=useState(false);
 const activeView=adminPreview?adminView:view;
 const callActual=(tab:string)=>navigate(tab);
 const previewNotice=<div className="cp-preview-notice"><span><Sparkles size={15}/> Prévia visual</span><p>Os dados abaixo são fictícios e servem apenas para validar a experiência.</p>{adminPreview&&<div><button onClick={()=>callActual('clientCatalog')}>Abrir serviços e planos</button></div>}{!adminPreview&&<div><button onClick={()=>callActual('vehiclehub')}>Abrir garagem atual</button><button onClick={()=>callActual('tracking')}>Acompanhamento atual</button></div>}</div>;
 const pageHeader=(eyebrow:string,heading:string,sub:string)=><header className="cp-page-head"><p className="cp-eyebrow">{eyebrow}</p><h1>{heading}</h1><p>{sub}</p></header>;
 const vehiclePhoto=<img src={heroImage} alt="Detalhe de um veículo em polimento, imagem ilustrativa"/>;
 const openReport=()=>window.print();

 return <main className={`main customer-preview ${activeView==='reportsPreview'?'customer-preview-report':''}`}>
  {previewNotice}
  {adminPreview&&<nav className="cp-demo-nav" aria-label="Telas demonstrativas da área do cliente">{([['customerHome','Início'],['garagePreview','Minha garagem'],['trackingPreview','Acompanhar serviço'],['reportsPreview','Relatórios'],['protectionsPreview','Proteções'],['benefitsPreview','Benefícios']] as const).map(([key,label])=><button key={key} className={activeView===key?'active':''} aria-current={activeView===key?'page':undefined} onClick={()=>setAdminView(key)}>{label}</button>)}</nav>}
  {activeView==='customerHome'&&<>
   <div className="cp-welcome"><div><p className="cp-eyebrow">ÁREA DO CLIENTE · PRÉVIA</p><h1>Bom dia, Marcos.</h1><p>Seu carro merece um cuidado exclusivo.</p></div><span className="cp-welcome-mark"><Sparkles size={23}/></span></div>
   <section className="cp-active-service" aria-label="Serviço em andamento"><div className="cp-active-copy"><span className="cp-live"><i/> ATENDIMENTO EM ANDAMENTO</span><h2>Seu Golf está conosco.</h2><p>Polimento técnico · Volkswagen Golf GTI</p><div className="cp-current-stage"><span>Etapa atual</span><strong>Serviço em execução</strong><span className="cp-progress"><i style={{width:'56%'}}/></span><small>Previsão de conclusão · Hoje, às 17h</small></div><Button onClick={()=>navigate('trackingPreview')}>Acompanhar serviço <ChevronRight size={17}/></Button></div><div className="cp-active-photo">{vehiclePhoto}<span><Clock3 size={14}/> Atualizado hoje, às 14:32</span></div></section>
   <section className="cp-home-grid"><article className="cp-vehicle-feature"><div className="cp-feature-photo">{vehiclePhoto}<span className="cp-photo-label"><Car size={15}/> VEÍCULO PRINCIPAL</span></div><div className="cp-feature-body"><div><p className="cp-eyebrow">SUA GARAGEM</p><h2>Volkswagen Golf GTI</h2><p>2022 <span>·</span> Cinza <span>·</span> RTA4D29</p></div><button className="cp-text-link" onClick={()=>navigate('garagePreview')}>Ver meu veículo <ChevronRight size={16}/></button></div></article>
    <div className="cp-home-side"><article className="cp-quiet-card"><span className="cp-icon"><CalendarDays size={19}/></span><div><span>ÚLTIMO ATENDIMENTO</span><strong>12 set 2026</strong><small>Polimento técnico</small></div></article><article className="cp-quiet-card"><span className="cp-icon"><ShieldCheck size={19}/></span><div><span>PROTEÇÃO DA PINTURA</span><strong><i className="cp-status-dot"/> Ativa</strong><small>Período contratado: 3 anos</small></div></article><article className="cp-quiet-card"><span className="cp-icon"><Sparkles size={19}/></span><div><span>PRÓXIMO CUIDADO</span><strong>Março de 2027</strong><small>Avaliação recomendada</small></div></article></div></section>
   <section className="cp-notifications"><div className="cp-section-title"><div><p className="cp-eyebrow">AO SEU CUIDADO</p><h2>Novidades do seu veículo</h2></div><Bell size={19}/></div><article><span className="cp-notification-icon"><FileText size={17}/></span><div><strong>Um novo relatório está disponível</strong><p>Inspeção Feijão Detailer · Volkswagen Golf GTI</p></div><button onClick={()=>navigate('reportsPreview')}>Ver relatório <ChevronRight size={16}/></button></article><article><span className="cp-notification-icon"><ShieldCheck size={17}/></span><div><strong>Avaliação de proteção recomendada em março</strong><p>Uma inspeção ajuda a acompanhar a conservação da vitrificação.</p></div><button onClick={()=>navigate('protectionsPreview')}>Ver proteção <ChevronRight size={16}/></button></article></section>
  </>}

  {activeView==='garagePreview'&&<>
   {pageHeader('SUA GARAGEM','Minha garagem','O histórico e os próximos cuidados de cada veículo, reunidos em um só lugar.')}
   <article className="cp-garage-card"><div className="cp-garage-photo">{vehiclePhoto}<span><Car size={15}/> VEÍCULO PRINCIPAL</span></div><div className="cp-garage-info"><div className="cp-garage-name"><div><p className="cp-eyebrow">VOLKSWAGEN · 2022</p><h2>Golf GTI</h2></div><span className="cp-plate">RTA4D29</span></div><div className="cp-detail-grid"><div><span>Cor</span><strong>Cinza</strong></div><div><span>Último atendimento</span><strong>12 set 2026</strong></div><div><span>Próximo cuidado</span><strong>Mar 2027 · avaliação</strong></div></div><Button variant="outline" onClick={()=>setExpanded(!expanded)}>{expanded?'Fechar prontuário':'Ver prontuário do veículo'} <ChevronRight size={16}/></Button></div></article>
   {expanded&&<section className="cp-record"><div className="cp-section-title"><div><p className="cp-eyebrow">PRONTUÁRIO DO VEÍCULO</p><h2>Volkswagen Golf GTI</h2></div><span className="cp-record-count">3 registros</span></div><div className="cp-record-list"><article><span className="cp-record-date">30 SET 2026</span><div><strong>Inspeção Feijão Detailer</strong><p>Polimento técnico, preparação da pintura e vitrificação.</p><button onClick={()=>navigate('reportsPreview')}>Abrir relatório <ChevronRight size={15}/></button></div><ShieldCheck size={18}/></article><article><span className="cp-record-date">12 SET 2026</span><div><strong>Polimento técnico</strong><p>Descontaminação e refino da pintura.</p></div><Wrench size={18}/></article><article><span className="cp-record-date">12 MAR 2026</span><div><strong>Proteção da pintura</strong><p>Vitrificação aplicada · avaliação recomendada em março/2027.</p></div><ShieldCheck size={18}/></article></div></section>}
   <section className="cp-evolution"><div className="cp-section-title"><div><p className="cp-eyebrow">HISTÓRICO VISUAL</p><h2>Evolução do seu veículo</h2><p>Arraste o controle para comparar as imagens.</p></div><Camera size={20}/></div><div className="cp-compare" style={{'--cp-split':`${compare}%`} as React.CSSProperties}><img className="cp-compare-after" src={washImage} alt="Imagem demonstrativa depois do serviço"/><div className="cp-compare-before">{vehiclePhoto}</div><span className="cp-compare-label before">ANTES · EXEMPLO</span><span className="cp-compare-label after">DEPOIS · EXEMPLO</span><span className="cp-compare-line"/><input type="range" aria-label="Comparar fotos de antes e depois" min="5" max="95" value={compare} onChange={e=>setCompare(Number(e.target.value))}/></div><div className="cp-compare-meta"><span>12 set 2026</span><strong>Polimento técnico</strong><span>Imagens ilustrativas da prévia</span></div></section>
  </>}

  {activeView==='trackingPreview'&&<>
   {pageHeader('ACOMPANHAMENTO','Seu veículo está conosco.','Acompanhe cada etapa do cuidado com o seu Golf GTI.')}
   <section className="cp-track-summary"><div className="cp-track-vehicle"><span className="cp-track-icon"><Car/></span><div><span>VEÍCULO · RTA4D29</span><h2>Volkswagen Golf GTI</h2></div></div><div className="cp-track-meta"><div><span>Serviço contratado</span><strong>Polimento técnico</strong></div><div><span>Entrada</span><strong>30 set 2026 · 09:10</strong></div><div><span>Previsão de conclusão</span><strong>Hoje, às 17h</strong></div></div></section>
   <section className="cp-timeline-panel"><div className="cp-section-title"><div><p className="cp-eyebrow">STATUS DO ATENDIMENTO</p><h2>Serviço em execução</h2></div><span className="cp-updated"><i/> Atualizado hoje, às 14:32</span></div><ol className="cp-timeline">{timeline.map((step,i)=><li className={i<3?'complete':i===3?'current':''} key={step}><span className="cp-step-dot">{i<3?<Check size={14}/>:i===3?<i/>:null}</span><div><strong>{step}</strong>{i===3&&<span>Etapa atual · previsão para finalizar às 16h</span>}{i===0&&<small>Hoje, às 09:10</small>}{i===1&&<small>Hoje, às 09:35</small>}{i===2&&<small>Hoje, às 11:05</small>}</div></li>)}</ol><div className="cp-update-note"><Clock3 size={17}/><div><strong>14:32 · Polimento da lateral direita finalizado.</strong><p>A equipe está concluindo o acabamento das demais áreas.</p></div></div><div className="cp-process-photo">{vehiclePhoto}<span><Camera size={15}/> Atualização visual · 14:32</span></div></section>
  </>}

  {activeView==='reportsPreview'&&<>
   {pageHeader('REGISTRO DO ATENDIMENTO','Inspeção Feijão Detailer','Um registro cuidadoso do serviço e das recomendações para o seu veículo.')}
   <article className="cp-report"><header className="cp-report-head"><img src={withBase("/feijao-detailer-logo.png")} alt="Feijão Detailer"/><span>RELATÓRIO DE SERVIÇO · DEMONSTRAÇÃO</span></header><div className="cp-report-vehicle"><div><p className="cp-eyebrow">VOLKSWAGEN · 2022</p><h2>Golf GTI</h2><span>RTA4D29 · Cinza</span></div><div><span>DATA DO ATENDIMENTO</span><strong>30 de setembro de 2026</strong></div><div><span>QUILOMETRAGEM</span><strong>Não informada</strong></div></div><div className="cp-report-columns"><section><h3>Condição encontrada</h3><ul><li>Pintura com contaminação moderada</li><li>Marcas superficiais</li><li>Plásticos externos ressecados</li><li>Vidros com marcas minerais</li></ul></section><section><h3>Serviços realizados</h3><ul className="cp-checklist"><li><CheckCircle2/>Descontaminação</li><li><CheckCircle2/>Polimento técnico</li><li><CheckCircle2/>Preparação da pintura</li><li><CheckCircle2/>Vitrificação</li></ul></section></div><section className="cp-report-observation"><h3>Observações do Detailer</h3><p>Durante a inspeção foram identificadas algumas marcas mais profundas que não poderiam ser removidas com segurança sem comprometer a camada de verniz.</p></section><section className="cp-report-care"><h3>Cuidados recomendados</h3><p>Evite lavagem pelo período recomendado após o serviço. Não utilize produtos abrasivos. Faça a manutenção periódica da proteção.</p><div><CalendarDays size={17}/><span>Próxima avaliação recomendada</span><strong>Março de 2027</strong></div></section><section className="cp-report-photos"><h3>Registro visual</h3><div><figure>{vehiclePhoto}<figcaption>Antes · ilustrativo</figcaption></figure><figure><img src={washImage} alt="Imagem demonstrativa após o serviço"/><figcaption>Depois · ilustrativo</figcaption></figure></div></section><footer className="cp-report-foot"><span>FEIJÃO DETAILER · CUIDADO AUTOMOTIVO</span><span>Documento demonstrativo</span></footer></article><div className="cp-report-actions"><Button onClick={openReport}><Download size={16}/> Baixar relatório em PDF</Button><small>Na prévia, o botão abre a janela de impressão para salvar como PDF.</small></div>
  </>}

  {activeView==='protectionsPreview'&&<>
   {pageHeader('CUIDADOS A LONGO PRAZO','Minhas proteções','Acompanhe os tratamentos aplicados e saiba quando vale a pena fazer uma avaliação.')}
   <section className="cp-protection-card"><div className="cp-protection-top"><span className="cp-protection-icon"><ShieldCheck/></span><div><p className="cp-eyebrow">VOLKSWAGEN GOLF GTI · RTA4D29</p><h2>Vitrificação da pintura</h2><span className="cp-protection-status"><i/> Proteção ativa</span></div><span className="cp-protection-menu">···</span></div><div className="cp-protection-bar"><div><span>Período contratado estimado</span><strong>3 anos</strong></div><div className="cp-protection-track"><i style={{width:'18%'}}/></div><div className="cp-protection-scale"><span>Aplicada em 12 mar 2026</span><span>Período estimado até mar 2029</span></div></div><div className="cp-protection-foot"><div><CalendarDays size={18}/><span>Próxima avaliação recomendada<strong>Março de 2027</strong></span></div><p>O período informado é uma referência contratada. A durabilidade real depende dos cuidados, uso e condições do veículo. A avaliação ajuda a verificar o estado da proteção.</p></div></section><section className="cp-other-protections"><div className="cp-section-title"><div><p className="cp-eyebrow">NO SEU VEÍCULO</p><h2>Outros tratamentos</h2></div></div><article><span className="cp-treatment-icon"><Sparkles/></span><div><strong>Vitrificação de plásticos</strong><span>Aplicada em 12 mar 2026</span></div><span className="cp-treatment-tag">Ativa</span></article><article><span className="cp-treatment-icon"><ShieldCheck/></span><div><strong>Cristalização dos vidros</strong><span>Sem aplicação registrada</span></div><span className="cp-treatment-tag muted">—</span></article><p className="cp-inline-note">Produtos e datas desta tela são demonstrativos. Informações reais dependerão do registro de cada atendimento.</p></section>
  </>}

  {activeView==='benefitsPreview'&&<>
   {pageHeader('RELACIONAMENTO','Benefícios Feijão','Uma forma especial de agradecer por compartilhar a Feijão Detailer.')}
   <section className="cp-benefit-card"><div className="cp-benefit-heading"><span className="cp-benefit-symbol"><Heart/></span><div><p className="cp-eyebrow">SUAS INDICAÇÕES</p><h2>Obrigado por recomendar.</h2><p>Quando alguém que você indica realiza um serviço, um benefício pode ficar disponível para você.</p></div></div><div className="cp-benefit-stats"><div><span>Clientes indicados</span><strong>3</strong></div><div><span>Indicações convertidas</span><strong>2</strong></div><div><span>Benefícios disponíveis</span><strong>1</strong></div><div><span>Já utilizados</span><strong>1</strong></div></div><div className="cp-benefit-available"><span className="cp-benefit-check"><Gift size={18}/></span><div><span>DISPONÍVEL</span><strong>Um cuidado especial para seu próximo serviço</strong><small>Consulte a equipe para conhecer as condições.</small></div><span className="cp-benefit-tag">1 benefício</span></div><div className="cp-referral"><div><span>SEU CÓDIGO DE CONVITE · DEMONSTRAÇÃO</span><strong>FD-MARCOS-26</strong><small>Este código é fictício e não está conectado a indicações reais.</small></div><Button variant="outline" onClick={()=>{void navigator.clipboard?.writeText('FD-MARCOS-26');setCopied(true)}}>{copied?<><Check size={16}/> Código copiado</>:<>Indicar um amigo <ArrowUpRight size={16}/></>}</Button></div></section>
   <div className="cp-benefit-footnote"><Gift size={18}/><p>Sem pontos ou catálogo de descontos: os benefícios são reconhecimentos pontuais, registrados conforme as regras da Feijão Detailer.</p></div>
  </>}
  <footer className="cp-page-foot"><span>FEIJÃO DETAILER</span><span>Um cuidado especial em cada etapa.</span><button onClick={()=>callActual('support')}>Falar com a equipe <ArrowUpRight size={15}/></button></footer>
 </main>;
}
