"use client";
import { apiFetch } from "@/lib/api";
import { AttachmentImage, AttachmentLink } from "./attachment";
import {useCallback,useEffect,useState} from 'react';
import {Car,Bell,History,Tag,Images,RefreshCw,CalendarDays,ArrowUpRight,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {serviceHistory,reminders,activeCampaign,type HubRecord,type HubBooking} from '../lib/vehicle-hub';
import './vehicle-hub.css';
type File={id:string;record_id:string;name:string;type:string;shared:number};
type Data={profile:{name:string}|null;accountKey?:string;records:HubRecord[];bookings:HubBooking[];files:File[]};
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((n||0)/100);
const date=(day:string|null)=>day?new Date(day.slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'Data não registrada';
const whatsapp=(message:string)=>'https://wa.me/5531993444280?text='+encodeURIComponent(message);
export default function VehicleHub({navigate}:{navigate:(tab:string)=>void}){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[vehicle,setVehicle]=useState('all'),[busy,setBusy]=useState(''),[detail,setDetail]=useState<HubRecord|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await apiFetch('/api/workflow',{cache:'no-store'}),j=await r.json() as Data&{error?:string};if(!r.ok)throw Error(j.error||'Não foi possível carregar seu veículo.');setData(j);setError('')}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 if(!data)return <main className="main vehicle-hub"><h1>Meus veículos</h1>{error?<><p role="alert" className="error">{error}</p><Button onClick={()=>void load()}>Tentar novamente</Button></>:<p role="status">Carregando seu histórico...</p>}</main>;
 const vehicles=data.records.filter(r=>r.kind==='vehicle');
 const matches=(id:unknown)=>vehicle==='all'||(vehicle==='unlinked'?!id:id===vehicle);
 const history=serviceHistory(data.records,data.bookings).filter(r=>matches(r.data.vehicleId));
 const notices=reminders(data.records,data.bookings).filter(n=>matches(n.vehicleId));
 const due=notices.filter(n=>n.due),future=notices.filter(n=>!n.due).sort((a,b)=>a.date.localeCompare(b.date));
 const unread=due.filter(n=>!n.read).length;
 const offers=data.records.filter(r=>activeCampaign(r));
 const selectedVehicle=vehicles.find(v=>v.id===vehicle);
 const orders=data.records.filter(r=>r.kind==='order'&&matches(r.data.vehicleId));
 const orderIds=new Set(orders.map(r=>r.id));
 const attachmentIds=new Set([...orderIds,...data.records.filter(r=>r.kind==='inspection'&&orderIds.has(r.parent_id||'')).map(r=>r.id)]);
 const photos=data.files.filter(f=>f.shared&&attachmentIds.has(f.record_id));
 const active=orders.filter(r=>!['entregue','cancelado'].includes(r.status));
 const unlinked=serviceHistory(data.records,data.bookings).some(r=>!r.data.vehicleId);
 const vehicleName=(id:string)=>vehicles.find(v=>v.id===id)?.data.title||'Veículo não vinculado';
 const read=async(id:string)=>{setBusy(id);try{const r=await apiFetch('/api/workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'read_notification',notificationId:id})});const j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível marcar o aviso.')}finally{setBusy('')}};
 return <main className="main vehicle-hub"><header className="top"><div><p className="eyebrow">ÁREA DO CLIENTE</p><h1>Meus veículos</h1><p className="hub-subtitle">Seu histórico, próximos cuidados e benefícios em um só lugar.</p></div><Button variant="outline" disabled={loading} onClick={()=>void load()} aria-label="Atualizar histórico"><RefreshCw size={16}/><span>Atualizar</span></Button></header>
 {error&&<p role="alert" className="error">{error}</p>}{loading&&<p role="status">Atualizando...</p>}
 {!data.profile&&<div className="hub-empty"><h2>Vamos conhecer seu veículo?</h2><p>Complete seu cadastro para reunir seus atendimentos aqui.</p><Button onClick={()=>navigate('garage')}>Cadastrar meu veículo</Button></div>}
 <section className="hub-vehicle"><div className="hub-vehicle-icon"><Car size={30}/></div><div className="hub-vehicle-info"><h2>{selectedVehicle?selectedVehicle.data.title:vehicle==='unlinked'?'Histórico sem veículo vinculado':'Todos os meus veículos'}</h2><p>{selectedVehicle?[selectedVehicle.data.plate,selectedVehicle.data.year,selectedVehicle.data.km?`${selectedVehicle.data.km} km`:null].filter(Boolean).join(' · '):`${vehicles.length} ${vehicles.length===1?'veículo cadastrado':'veículos cadastrados'}`}</p>{selectedVehicle?.data.protection&&<p>Proteção: {selectedVehicle.data.protection}</p>}</div><div className="hub-selector"><label id="vehicle-label">Consultar veículo</label><Select value={vehicle} onValueChange={setVehicle}><SelectTrigger aria-labelledby="vehicle-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os veículos</SelectItem>{vehicles.map(v=><SelectItem key={v.id} value={v.id}>{v.data.title}{v.data.plate?` · ${v.data.plate}`:''}</SelectItem>)}{unlinked&&<SelectItem value="unlinked">Sem veículo vinculado</SelectItem>}</SelectContent></Select><button className="hub-text-button" onClick={()=>navigate('garage')}>Gerenciar meus veículos</button></div></section>
 <div className="hub-summary"><div><History size={20}/><strong>{history.length}</strong><span>atendimentos realizados</span></div><div><Bell size={20}/><strong>{unread}</strong><span>avisos não lidos</span></div><div><Tag size={20}/><strong>{offers.length}</strong><span>campanhas disponíveis</span></div></div>
 <Tabs defaultValue="history"><TabsList className="hub-tabs" aria-label="Informações do veículo"><TabsTrigger value="history"><History size={17}/>Histórico</TabsTrigger><TabsTrigger value="notifications"><Bell size={17}/>Lembretes{unread>0&&<span className="hub-count">{unread}</span>}</TabsTrigger><TabsTrigger value="campaigns"><Tag size={17}/>Campanhas</TabsTrigger><TabsTrigger value="files"><Images size={17}/>Fotos e documentos</TabsTrigger></TabsList>
 <TabsContent value="history"><div className="hub-section-heading"><h2>Serviços realizados</h2><p>Do atendimento mais recente ao mais antigo.</p></div>{history.length?<div className="hub-history">{history.map(r=><article className="hub-history-card" key={r.id}><div className="hub-history-date"><CalendarDays size={18}/><span>{date(r.completedDay)}</span></div><div><span className="hub-status">Concluído</span><h3>{r.data.title}</h3><p className="hub-muted">{vehicleName(r.data.vehicleId)}</p><ul>{(r.data.items||[]).map((i:{name:string;qty:number},index:number)=><li key={index}>{i.qty>1?`${i.qty}× `:''}{i.name}</li>)}</ul></div><div className="hub-history-actions"><strong>{money(r.data.total)}</strong><Button variant="outline" onClick={()=>setDetail(r)}>Ver atendimento</Button></div></article>)}</div>:<div className="hub-empty"><History/><h3>Nenhum serviço concluído por aqui</h3><p>Assim que um atendimento for finalizado e vinculado à sua conta, ele aparecerá neste histórico.</p><Button variant="outline" onClick={()=>navigate('appointments')}>Meus agendamentos</Button></div>}{!history.length&&data.accountKey&&<p className="hub-footnote">Se você já atendia na Feijão Detailer, envie este identificador à equipe para conferirem e, se aprovado, vincularem seu histórico: <strong>{data.accountKey}</strong></p>}
 {active.length>0&&<section className="hub-active"><h2>Em atendimento</h2>{active.map(r=><div key={r.id}><span>{r.data.title}</span><span className="hub-status">{r.status}</span></div>)}<Button variant="outline" onClick={()=>navigate('tracking')}>Acompanhar serviço</Button></section>}
 {unlinked&&<p className="hub-footnote">Há atendimentos antigos sem veículo vinculado. Você pode vê-los em “Todos os veículos” ou “Sem veículo vinculado”. A Feijão Detailer pode completar esse vínculo.</p>}</TabsContent>
 <TabsContent value="notifications"><div className="hub-section-heading"><h2>Próximos cuidados</h2><p>Avisos de 15 e 30 dias após a realização do serviço, disponíveis aqui no painel.</p></div><div className="hub-notices">{due.map(n=><article className={`hub-notice ${n.read?'is-read':''}`} key={n.id}><Bell size={22}/><div><span className="hub-status">{n.read?'Lido':'Novo aviso'} · {date(n.date)}</span><h3>{n.days} dias de cuidado com seu veículo</h3><p>{n.days===15?'Como está o resultado do atendimento? Fale com a gente para tirar dúvidas sobre os cuidados.':'Que tal conferir o próximo cuidado do seu veículo? Consulte a equipe sobre a manutenção indicada.'}</p><small>{n.title} · {vehicleName(n.vehicleId)}</small><div className="hub-actions"><a className="hub-contact" target="_blank" rel="noreferrer" href={whatsapp(`Olá! Recebi o lembrete de ${n.days} dias do serviço ${n.title}. Gostaria de conversar sobre os cuidados do meu veículo.`)}>Conversar com a equipe <ArrowUpRight size={16}/></a>{!n.read&&<Button variant="outline" disabled={!!busy} onClick={()=>void read(n.id)}><Check size={16}/>{busy===n.id?'Salvando...':'Marcar como lido'}</Button>}</div></div></article>)}</div>{!due.length&&<div className="hub-empty"><Bell/><h3>Nenhum aviso por enquanto</h3><p>Os lembretes ficam disponíveis ao completar 15 e 30 dias de cada atendimento.</p></div>}{future.length>0&&<section className="hub-active"><h2>Lembretes programados</h2>{future.map(n=><div key={n.id}><span>{n.days} dias · {n.title}</span><strong>{date(n.date)}</strong></div>)}</section>}</TabsContent>
 <TabsContent value="campaigns"><div className="hub-section-heading"><h2>Campanhas e descontos</h2><p>Confira os benefícios e as condições antes de solicitar seu atendimento.</p></div>{offers.length?<div className="hub-offers">{offers.map(c=><article className="hub-offer" key={c.id}><span className="hub-offer-label"><Tag size={18}/>{c.data.offer}</span><h3>{c.data.title}</h3><p>{c.data.description}</p><strong>Válido até {date(c.data.ends)}</strong><p className="hub-muted">{c.data.terms}</p><a className="hub-contact" href={whatsapp(`Olá! Tenho interesse na campanha ${c.data.title}: ${c.data.offer}. Podemos confirmar as condições e a disponibilidade?`)} target="_blank" rel="noreferrer">Consultar campanha <ArrowUpRight size={16}/></a></article>)}</div>:<div className="hub-empty"><Tag/><h3>Nenhuma campanha ativa no momento</h3><p>Os descontos e novidades da Feijão Detailer aparecerão aqui quando forem lançados.</p></div>}</TabsContent>
 <TabsContent value="files"><div className="hub-section-heading"><h2>Fotos e documentos</h2><p>Registros dos atendimentos compartilhados pela equipe.</p></div>{photos.length?<div className="hub-files">{photos.map(f=><AttachmentLink key={f.id} id={f.id}>{f.type.startsWith('image/')?<AttachmentImage id={f.id} alt={f.name}/>:<Images size={30}/>}<span>{f.name}</span><small>Abrir arquivo ↗</small></AttachmentLink>)}</div>:<div className="hub-empty"><Images/><h3>Nenhum arquivo compartilhado ainda</h3><p>As fotos e os documentos do veículo ficam reunidos aqui após a equipe compartilhá-los.</p></div>}</TabsContent></Tabs>
 <footer className="hub-links"><Button variant="outline" onClick={()=>navigate('myquotes')}>Meus orçamentos</Button><Button variant="outline" onClick={()=>navigate('myplan')}>Meu plano</Button><Button variant="outline" onClick={()=>navigate('support')}>Atendimento</Button></footer>
 <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="hub-dialog"><DialogHeader><DialogTitle>{detail?.data.title}</DialogTitle><DialogDescription>Resumo do atendimento concluído</DialogDescription></DialogHeader>{detail&&<><p>{vehicleName(detail.data.vehicleId)}</p><p>{date(serviceHistory(data.records,data.bookings).find(r=>r.id===detail.id)?.completedDay||null)}</p><ul>{(detail.data.items||[]).map((i:{name:string;qty:number;price:number},index:number)=><li key={index}>{i.qty}× {i.name} — {money(i.qty*i.price)}</li>)}</ul><strong>Total: {money(detail.data.total)}</strong><p>{detail.data.notes}</p>{detail.data.checkOut?.length>0&&<p>Conferência de entrega: {detail.data.checkOut.join(', ')}</p>}{detail.data.maintenanceDate&&<p>Manutenção indicada: {date(detail.data.maintenanceDate)}</p>}<a className="hub-contact" target="_blank" rel="noreferrer" href={whatsapp(`Olá! Gostaria de conversar sobre o atendimento ${detail.data.title}.`)}>Falar sobre este atendimento <ArrowUpRight size={16}/></a></>}</DialogContent></Dialog>
 </main>;
}
