"use client";
import { withBase } from "@/lib/base";
import { apiFetch, signInWithGoogle, signOutEverywhere } from "@/lib/api";
import { useEffect,useState,type ReactNode } from "react";
import { Menu,LayoutDashboard,CalendarDays,Users,Car,ClipboardList,Package,CreditCard,Wallet,Settings,MessageCircle,Wrench,Info,LogIn,LogOut,FileText,House,ShieldCheck,Star,type LucideIcon } from "lucide-react";
import { Sheet,SheetContent,SheetTitle,SheetTrigger } from "@/components/ui/sheet";
import { WorkspaceContext } from "./workspace-context";
import ServicesPage from "./services";
import Dashboard from "./dashboard";
import Operations from "./operations";
import VehicleHub from "./vehicle-hub";
import CustomerPortalPreview from "./customer-portal-preview";
import CustomerAuth from "./customer-auth";
import ClientAreaHome from "./client-area-home";
import CustomerReviews from "./customer-reviews";
import FinancePanel from "./finance-panel";
import "./workspace.css";
import "./dashboard.css";
import "./designer-refresh.css";
const publicTabs=[['clientCatalog','Área do Cliente',House],['about','Sobre nós',Info]] as const;
const adminTabs=[['overview','Visão geral',LayoutDashboard],['messages','Mensagens e campanhas',MessageCircle],['schedule','Agenda',CalendarDays],['clientes','Clientes',Users],['quotes','Orçamentos',FileText],['orders','Ordens de serviço',ClipboardList],['servicos','Catálogo e preços',Wrench],['subscriptions','Assinaturas',CreditCard],['followups','Manutenção de vitrificação',MessageCircle],['finance','Financeiro',Wallet],['financeiro','Lançamentos rápidos',Wallet],['inventory','Rendimento de produtos',Package],['reports','Relatórios',FileText],['settings','Configurações',Settings],['customerPreview','Prévia da área do cliente',Car]] as const;
const customerAreaTabs=[['customerHome','Início',House],['clientCatalog','Serviços e planos',Wrench],['vehiclehub','Minha garagem',Car],['appointments','Agendamentos',CalendarDays],['tracking','Acompanhar serviço',ClipboardList],['myquotes','Orçamentos',FileText],['myplan','Meus planos',CreditCard],['followups','Cuidados e proteções',ShieldCheck],['customerReviews','Avaliações',Star]] as const;
export default function Workspace({initial='services',about}:{initial?:string;about?:ReactNode}){
 const startCatalogView=initial==='plans'?'planos':initial==='package'?'pacote':initial==='agendar'?'agendar':'destaques';
 const [tab,setTab]=useState(['services','plans','package'].includes(initial)?'clientCatalog':initial),[catalogView,setCatalogView]=useState(startCatalogView),[session,setSession]=useState<{admin:boolean;signedIn:boolean;name:string}|null>(null),[open,setOpen]=useState(false),[historyReview,setHistoryReview]=useState(false);
 useEffect(()=>{apiFetch('/api/session').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{admin:boolean;signedIn:boolean;name:string}>}).then(s=>{setSession(s);if(initial==='admin')setTab(s.admin?'overview':s.signedIn?'customerHome':'customerAuth')}).catch(()=>setSession({admin:false,signedIn:false,name:''}))},[initial]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('revisar-cadastro')==='1'){setHistoryReview(true);window.history.replaceState({},'',window.location.pathname)}},[]);
 const navigate=(next:string)=>{const view=next==='clientBooking'?'agendar':next==='plans'||next==='clientPlans'?'planos':next==='package'||next==='clientPackage'?'pacote':next==='services'||next==='clientCatalog'?'destaques':null;if(view){setCatalogView(view);setTab('clientCatalog')}else setTab(next);setOpen(false);window.scrollTo({top:0,behavior:'instant'})};
 const navButton=([key,label,Icon]:readonly [string,string,LucideIcon])=><button className={`nav ${tab===key?'active':''}`} aria-current={tab===key?'page':undefined} onClick={()=>navigate(key)} key={key}><Icon size={18}/>{label}</button>;
 const menu=<><button className="brand" onClick={()=>navigate(session?.signedIn&&!session.admin?'customerHome':'clientCatalog')}><img className="brand-logo" src={withBase("/feijao-detailer-logo.png")} alt="Feijão Detailer"/></button><div className="role-label">{session?.admin?'ADMINISTRADOR':session?.signedIn?'ÁREA DO CLIENTE':'BEM-VINDO'}</div><nav aria-label="Abas do painel">{session?.admin&&<div className="side-note">GESTÃO</div>}{session?.admin?adminTabs.map(navButton):session?.signedIn?<><div className="side-note">ÁREA DO CLIENTE</div>{customerAreaTabs.map(navButton)}<div className="side-divider"/>{navButton(['about','Sobre nós',Info])}</>:<><div className="side-note">FEIJÃO DETAILER</div>{publicTabs.map(navButton)}</>}</nav><div className="side-foot">{session?.signedIn&&!session.admin?<><span>{session.name}</span><button className="nav" onClick={async()=>{await signOutEverywhere();window.location.reload()}}><LogOut size={18}/>Sair</button></>:session?.admin?<><span>{session.name}</span><button className="nav" onClick={async()=>{await signOutEverywhere();window.location.assign(withBase('/'))}}><LogOut size={18}/>Sair</button><span className="side-note">SITE</span>{publicTabs.map(navButton)}</>:<><button className="nav" onClick={()=>navigate('customerAuth')}><LogIn size={18}/>Entrar / Primeiro acesso</button><button className="nav" onClick={()=>void signInWithGoogle('/admin/')}><LogIn size={18}/>Acesso da gestão</button></>}<a className="side-contact" href="https://wa.me/5531993444280" target="_blank" rel="noreferrer"><MessageCircle size={18}/>WhatsApp</a></div></>;
 return <WorkspaceContext.Provider value={{navigate}}><div className={`site-shell unified-shell ${session?.admin ? "admin-experience" : session?.signedIn ? "client-experience" : "public-experience"}`}><a className="skip-navigation" href="#page-content">Pular para conteúdo</a><aside className="side site-sidebar">{menu}</aside><div className="site-content" id="page-content" onClick={e=>{const a=(e.target as HTMLElement).closest('a');const href=a?.getAttribute('href');const paths:Record<string,string>={'/':session?.signedIn&&!session.admin?'customerHome':'clientCatalog','/planos':'clientPlans','/sobre-nos':'about','/admin':session?.admin?'overview':session?.signedIn?'customerHome':'customerAuth'};if(href&&paths[href]){e.preventDefault();navigate(paths[href])}}}><div className="site-mobile-bar"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger aria-label="Abrir menu"><Menu/></SheetTrigger><SheetContent side="left" className="site-mobile-drawer"><SheetTitle className="sr-only">Menu</SheetTitle><div className="side mobile-side">{menu}</div></SheetContent></Sheet><span>Feijão Detailer</span></div>{historyReview&&<p className="customer-auth-notice" role="status">Seu acesso foi criado, mas encontramos um cadastro anterior com o mesmo telefone. O histórico não foi conectado automaticamente; fale com a equipe para conferir e fazer o vínculo seguro.</p>}{tab==='clientCatalog'?<ServicesPage key={catalogView} initialTab={catalogView}/>:tab==='about'?about:!session?<main className="main"><p>Verificando acesso...</p></main>:!session.signedIn?<CustomerAuth/>:session.admin&&tab==='customerPreview'?<CustomerPortalPreview view="customerHome" navigate={navigate} adminPreview/>:session.admin&&tab==='finance'?<main className="main management-page"><FinancePanel/></main>:session.admin&&tab==='financeiro'?<main className="main management-page"><FinancePanel quick/></main>:session.admin&&['clientes','servicos'].includes(tab)?<Dashboard selectedTab={tab}/>:!session.admin&&tab==='customerHome'?<ClientAreaHome navigate={navigate}/>:!session.admin&&tab==='customerReviews'?<CustomerReviews/>:!session.admin&&tab==='vehiclehub'?<VehicleHub navigate={navigate}/>:<Operations key={tab} tab={tab} admin={session.admin} navigate={navigate}/>}</div></div></WorkspaceContext.Provider>;
}

