-- Feijão Detailer · esquema inicial (Supabase / PostgreSQL)
--
-- O site é estático (GitHub Pages). Todo acesso aos dados passa pela Edge Function
-- `api`, que usa a conexão privilegiada do projeto. Por isso as tabelas ficam com
-- RLS ligado e SEM políticas: a chave pública (anon) não lê nem escreve nada direto.

create table if not exists public.clients (
  id integer generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  vehicle text not null default '',
  plate text not null default '',
  notes text not null default '',
  user_id text,
  email text not null default '',
  address text not null default '',
  referred_by_client_id integer
);
create unique index if not exists idx_clients_user on public.clients (user_id);

create table if not exists public.referral_events (
  id integer generated by default as identity primary key,
  client_id integer not null,
  referred_client_id integer,
  event_type text not null,
  description text not null,
  created_at text not null
);
create index if not exists idx_referral_events_client on public.referral_events (client_id, created_at);

create table if not exists public.services (
  id integer generated by default as identity primary key,
  name text not null,
  category text not null default 'Serviços',
  price integer not null default 0,
  duration integer not null default 60,
  booking_duration integer not null default 30,
  description text not null default ''
);
create unique index if not exists idx_services_name on public.services (name);

create table if not exists public.bookings (
  id integer generated by default as identity primary key,
  client_id integer not null,
  service_id integer not null,
  start_at text not null,
  booking_duration integer,
  status text not null default 'agendado',
  amount integer not null default 0,
  paid integer not null default 0,
  notes text not null default ''
);
create index if not exists idx_bookings_start on public.bookings (start_at);
create index if not exists idx_bookings_client on public.bookings (client_id);

create table if not exists public.transactions (
  id integer generated by default as identity primary key,
  date text not null,
  kind text not null,
  category text not null default '',
  description text not null,
  amount integer not null,
  booking_id integer,
  subcategory text not null default '',
  payment_method text not null default '',
  financial_status text not null default 'pago',
  notes text not null default '',
  is_stock_purchase integer not null default 0,
  is_recurring integer not null default 0,
  recurrence_key text,
  record_id text
);
create index if not exists idx_transactions_date_status on public.transactions (date, financial_status);

create table if not exists public.financial_categories (
  id integer generated by default as identity primary key,
  name text not null,
  type text not null default 'saida',
  active integer not null default 1
);
create unique index if not exists idx_financial_categories_name_type on public.financial_categories (name, type);

create table if not exists public.plan_subscriptions (
  id integer generated by default as identity primary key,
  client_id integer not null,
  plan_service_id integer not null,
  status text not null default 'pendente',
  amount integer not null,
  requested_at text not null,
  authorized_at text,
  expires_at text
);
create index if not exists idx_plan_subscriptions_status on public.plan_subscriptions (status);

create table if not exists public.workflow_records (
  id text primary key,
  kind text not null,
  client_id integer,
  parent_id text,
  status text not null default 'aberto',
  data jsonb not null default '{}'::jsonb,
  version integer not null default 1,
  created_at text not null,
  updated_at text not null
);
create index if not exists idx_workflow_kind_client on public.workflow_records (kind, client_id);
create index if not exists idx_workflow_parent on public.workflow_records (parent_id);

create table if not exists public.audit_log (
  id integer generated by default as identity primary key,
  actor text not null,
  action text not null,
  record_id text not null,
  created_at text not null
);

create table if not exists public.service_interest (
  service_name text primary key,
  clicks integer not null default 0,
  updated_at text not null
);

create table if not exists public.attachments (
  id text primary key,
  record_id text not null,
  client_id integer not null,
  name text not null,
  type text not null,
  shared integer not null default 0,
  created_at text not null
);
create index if not exists idx_attachments_client_record on public.attachments (client_id, record_id);

-- Nenhuma política: só a Edge Function (chave de serviço / conexão direta) acessa os dados.
alter table public.clients enable row level security;
alter table public.referral_events enable row level security;
alter table public.services enable row level security;
alter table public.bookings enable row level security;
alter table public.transactions enable row level security;
alter table public.financial_categories enable row level security;
alter table public.plan_subscriptions enable row level security;
alter table public.workflow_records enable row level security;
alter table public.audit_log enable row level security;
alter table public.service_interest enable row level security;
alter table public.attachments enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

-- Armazenamento privado para anexos das ordens de serviço e cópias de segurança diárias.
insert into storage.buckets (id, name, public, file_size_limit)
values ('attachments', 'attachments', false, 6291456),
       ('backups', 'backups', false, 52428800)
on conflict (id) do nothing;
